### ISSUE TITLE
ElectronicValueRW: Extended error codes have OPOS_ prefix

### ISSUE THREAD

**Issue by mjpcger** [JavaPOSWorkingGroup/javapos-contracts#14]
The ExtenderError constants for the ElectronicValueRW device class have names starting with OPOS_. This is probably wrong. The names shoud be the names as specified in the UPOS specification.
In addition: There are error codes OPOS_EVRW_NOCARD and OPOS_EVRW_RELEASE defined, but I cannot find any related specification for extender errors EVRW_NOCARD or EVRW_RELEASE within the UPOS specification. These values should be removed or otherwise marked as deprecated or so.

**Comment by kuniss** [comment]
@mjpcger, I'm going to correct this!

**Comment by kuniss** [comment]
`EVRW_NOCARD` is mentioned in `endDetection()`.
`EVRW_RELEASE` is mentioned at `endRemoval()`.
So, no need to mark them as deprecated. 😄 
However, they should be listed in the chapter of extended error code for ErrorEvents.

**Comment by kuniss** [comment]
Solved with release [1.15.0](https://github.com/JavaPOSWorkingGroup/javapos-contracts/releases/tag/1.15.0).
