### ISSUE TITLE
Some Enumerated Tag Values For ElectronicValueRW Are Missing

### ISSUE THREAD

**Issue by mjpcger** [JavaPOSWorkingGroup/javapos-contracts#16]
The following constants are missing in ElectronicValueRWConst.java (UPOS version 1.15):
EVRW_TAG_TT_COMPLETION
EVRW_TAG_TT_PRE_SALES
Keep in mind: EVRW_TAG_TT_PRE_SALES is specified as EVRW_TAG_TT_PRE-SALES within UPOS specification, however, a '-' cannot be part of a constant and should be replaced by '_'.

**Comment by kuniss** [comment]
The '-' issue has been filed into the UnifiedPOS task tracker as [UPOS1151-17](https://issues.omg.org/browse/UPOS1151-17) issue and will be corrected for UnifiedPOS 1.16.

**Comment by kuniss** [comment]
@mjpcger, seems we forgot these 2 constants too...

**Comment by kuniss** [comment]
We should use the same values as defined at 
https://github.com/kunif/OPOS-CCO/blob/cc11716c2cd0c367e84945dde3a3ad0d90d48360/Common/Opos/OposEvrw.h#L247
and
https://github.com/kunif/OPOS-CCO/blob/cc11716c2cd0c367e84945dde3a3ad0d90d48360/Common/Opos/OposEvrw.h#L248

**Comment by kuniss** [comment]
Solved with release [1.15.1](https://github.com/JavaPOSWorkingGroup/javapos-contracts/releases/tag/1.15.1).
