### ISSUE TITLE
Some Enumerated Tag Values For ElectronicValueRW Are Missing in JavaPOS version 1.14

### ISSUE THREAD

**Issue by mjpcger** [JavaPOSWorkingGroup/javapos-contracts#17]
The following constants are missing in ElectronicValueRWConst.java (UPOS version 1.14):
EVRW_TAG_NIT_ALL
EVRW_TAG_NIT_UPDATED

**Comment by kuniss** [comment]
This will be added to version 1.15 release as it is shortly before release and its not worth to make another 1.14 correction release as no one else complained about it, especially no one from Japan which is the main country for using these kind of devices.

**Comment by kuniss** [comment]
@mjpcger, did we forget this 2 constants to add? I do not find them in the source code and here is not reference...

**Comment by kuniss** [comment]
We should use the same constant values as defined at 
https://github.com/kunif/OPOS-CCO/blob/f0a163740bc0dd6b6158029dddd318dec8c09d76/Common/Opos/OposEvrw.h#L138
and
https://github.com/kunif/OPOS-CCO/blob/f0a163740bc0dd6b6158029dddd318dec8c09d76/Common/Opos/OposEvrw.h#L139

**Comment by kuniss** [comment]
Solved with release [1.15.1](https://github.com/JavaPOSWorkingGroup/javapos-contracts/releases/tag/1.15.1).
