### ISSUE TITLE
Scale Constant SCAL_SUE_UNDERWEIGHT Missing

### ISSUE THREAD

**Issue by mjpcger** [JavaPOSWorkingGroup/javapos-contracts#18]
The Scale constant SCAL_SUE_UNDERWEIGHT is still missing. I don't really remember when, but I think I reported it at least one year or more ago. Has not been specified in OPOS-CCO as well, so can be set to any unique value, e.g. 17

**Comment by kuniss** [comment]
The constant you are looking out for is `SCAL_SUE_WEIGHT_UNDERWEIGHT` and was added at [1.14.4](https://github.com/JavaPOSWorkingGroup/javapos-contracts/releases/tag/1.14.4). 😄
