### ISSUE TITLE
PINPad: DataEvent constant PPAD_TIMEOUT missing.

### ISSUE THREAD

**Issue by mjpcger** [JavaPOSWorkingGroup/javapos-contracts#19]
The constant PPAD_TIMEOUT for use in DataEvent status value has not been defined in PINPadConst.java.
Following line needs to be added to src/main/java/jpos/PINPadConst.java at line 97:

    public static final int PPAD_TIMEOUT                    = 3;

**Comment by mjpcger** [comment]
Still not defined in OPOS-CCO/Common/Opos/OposPPad.h, therefore PPAD_TIMEOUT = 3 should really be the correct value.

**Comment by kuniss** [comment]
Correct, this constant needs to be added.

**Comment by kuniss** [comment]
Fixed and released in https://github.com/JavaPOSWorkingGroup/javapos-contracts/releases/tag/1.15.2
