### ISSUE TITLE
Missing constants for FiscalPrinter

### ISSUE THREAD

**Issue by mjpcger** [JavaPOSWorkingGroup/javapos-contracts#8]
The following FiscalPrinter constants have been specified in UPOS 1.14, but are not present in JavaPOS 1.14:
**FPTR_AC_SEK**, **FPTR_CC_SWEDEN**, **FPTR_S_JOURNAL_SLIP**, **FPTR_S_RECEIPT_SLIP**, **FPTR_AT_DISCOUNT** and **FPTR_AT_SURCHARGE**
To **FPTR_AC_SEK** and **FPTR_CC_SWEDEN**: perhaps not so important because Sweden uses fiscal boxes, not fiscal printers and OTHER is probably a good alternative. However, I heard of implementations as fiscal printer without any print station.
To **FPTR_S_JOURNAL_SLIP** and **FPTR_S_RECEIPT_SLIP**: May be this is a theoretical problem, I don't know any fiscal printer which supports document printing, except some very old models that are no longer in use.
To **FPTR_AT_DISCOUNT** and **FPTR_AT_SURCHARGE**: It is completely unclear which constant could be used instead for package adjustments.

**Comment by kuniss** [comment]
Source code review shows:

**FPTR_AC_SEK**: is lacking in [FiscalPrinterConst](https://github.com/JavaPOSWorkingGroup/javapos-contracts/blob/9d7e9ccfdf6880410cf23a0e6055cf396f0a8d6d/src/main/java/jpos/FiscalPrinterConst.java), but defined in the UnfiedPOS specification.

**FPTR_CC_SWEDEN**: is lacking in [FiscalPrinterConst](https://github.com/JavaPOSWorkingGroup/javapos-contracts/blob/9d7e9ccfdf6880410cf23a0e6055cf396f0a8d6d/src/main/java/jpos/FiscalPrinterConst.java), but defined in the UnfiedPOS specification.

**FPTR_S_JOURNAL_SLIP**: is lacking in [FiscalPrinterConst](https://github.com/JavaPOSWorkingGroup/javapos-contracts/blob/9d7e9ccfdf6880410cf23a0e6055cf396f0a8d6d/src/main/java/jpos/FiscalPrinterConst.java), but defined in the UnfiedPOS specification as enumeration constant of the property _ErrorStation_.

**FPTR_S_RECEIPT_SLIP**: is lacking in [FiscalPrinterConst](https://github.com/JavaPOSWorkingGroup/javapos-contracts/blob/9d7e9ccfdf6880410cf23a0e6055cf396f0a8d6d/src/main/java/jpos/FiscalPrinterConst.java) but defined in the UnfiedPOS specification as enumeration constant of the property _ErrorStation_.

**FPTR_AT_DISCOUNT**: is lacking in [FiscalPrinterConst](https://github.com/JavaPOSWorkingGroup/javapos-contracts/blob/9d7e9ccfdf6880410cf23a0e6055cf396f0a8d6d/src/main/java/jpos/FiscalPrinterConst.java) but defined in the UnfiedPOS specification as argument enumeration value for parameter _adjustmentType_ of methods _printRecPackageAdjustment_ and _printRecPackageAdjustVoid_. 
This is assumed to be an (quite old) issue in the UnifiedPOS specification as other methods like _printRecItemAdjustment_ define other enumeration constants (e.g., FPTR_AT_AMOUNT_DISCOUNT, FPTR_AMOUNT_SURCHARGE, FPTR_AT_PERCENTAGE_DISCOUNT, FPTR_PERCENTAGE_SURCHARGE etc.), all well defined in JavaPOS, which are intended to be used for _printRecPackageAdjustment_  and _printRecPackageAdjustVoid_ too. So an UnifiedPOS specification corrections is appreciated here listing the same enumeration constants for _printRecPackageAdjustment_  and _printRecPackageAdjustVoid_ as for _printRecItemAdjustment_.

**FPTR_AT_SURCHARGE**: same as for FPTR_AT_DISCOUNT.

**Comment by kuniss** [comment]
The problem reagrding **FPTR_AT_DISCOUNT** and **FPTR_AT_SURCHARGE** and a potential improvment of the UnifiedPOS specification mentioned here had been discussed at the quartely meeting of the OMG Retail Domain Task Force.

The conclusion is that the task force might not change the UnifiedPOS specification because this issue is quite old (at least 15 years) and no one had a concern yet. 

So now, only the correction will be maded for the JavaPOS implementation by defining the both `FPTR_AT_DISCOUNT` and `FPTR_AT_DISCOUNT ` as stated in the first comment.

**Comment by kuniss** [comment]
Now finally solved with release [1.15.0](https://github.com/JavaPOSWorkingGroup/javapos-contracts/releases/tag/1.15.0).
