### ISSUE TITLE
Bad Gate property GetStatus

### ISSUE THREAD

**Issue by mjpcger** [JavaPOSWorkingGroup/javapos-contracts#9]
The getter for the Gate property GateStatus has not been implemented. Instead, a getter getGetStatus has been implemented, although a property GetStatus does not exist in the UPOS specification. I assume that GetStatus means GateStatus, but this is only an assumption.

**Comment by kuniss** [comment]
Yes, this is right. 
The `getGetStatus` is wrong and `getGateStatus` is missing at all.
Needs to be fixed.

**Comment by kuniss** [comment]
Will not be fixed for JavaPOS 1.14 anymore as it would break the interface-name based versioning scheme.

Instead it will be added to the upcoming 1.15 library version.

**Comment by kuniss** [comment]
Solved with release [1.15.0](https://github.com/JavaPOSWorkingGroup/javapos-contracts/releases/tag/1.15.0).
